export const TAGS = [
    "Spiritual",
    "Tech",
    "News",
    "Coding",
    "Books",
    "Company",
    "School",
    "Food",
    "Pets",
    "Music",
    "Crafts",
    "Travel",
    "Science",
    "Fitness",
    "NSFW",
    "Education",
    "Photography",
    "Humor",
    "Politics",
    "Nature",
    "Literature",
    "e-Commerce",
    "Film / TV",
    "Fashion / Beauty",
    "Art / Design",
    "Games / Apps",
    ];